export const data = [
  {
    nama: "Drs. H. HENDRA S GUMILANG.,MM",
    ket: "KEPALA BADAN",
    posisi: "Peserta",
  },
  { nama: "BUDIMAN RAHAYU, AP", ket: "SEKTERARIS", posisi: "Peserta" },
  { nama: "DEWI MARTIA NINGSIH, SE.,M.Si", ket: "WASRIK", posisi: "Peserta" },
  { nama: "Hj. ATI RAHMAWATI, SE, M.Si", ket: "WASRIK", posisi: "Peserta" },
  { nama: "Hj. LILIS YULIA. S.IP., MM", ket: "WASRIK", posisi: "Peserta" },
  { nama: "MOCH. HENDRIYANTO BW SH., MH", ket: "WASRIK", posisi: "Peserta" },
  { nama: "RISWANTO DANIARSA, S.IP", ket: "WASRIK", posisi: "Peserta" },
  { nama: "DIANA INRA, SE", ket: "WASRIK", posisi: "Peserta" },
  {
    nama: "R. RAHMAT FADLI SADIKIN, A.Md.,A.Pj",
    ket: "WASRIK",
    posisi: "Peserta",
  },
  { nama: "RIO FAUZI RESMANA, SE", ket: "WASRIK", posisi: "Peserta" },
  { nama: "KIKI MUSTIKAWATI", ket: "WASRIK", posisi: "Peserta" },
  { nama: "RIDA APRIANNY, SE", ket: "WASRIK", posisi: "Peserta" },
  { nama: "HENDRA JULIANSYAH", ket: "WASRIK", posisi: "Peserta" },
  { nama: "KUSMAYADI, S.IP", ket: "SEKRETARIAT", posisi: "Peserta" },
  { nama: "DIAN MIFTAH AL BAROKAH", ket: "SEKRETARIAT", posisi: "Peserta" },
  {
    nama: "YUSMININGSIH NURBAETI, S.Sos",
    ket: "TEKNOLOGI INFORMASI",
    posisi: "Peserta",
  },
  {
    nama: "ADAM MUHARAM, S.Sos",
    ket: "TEKNOLOGI INFORMASI",
    posisi: "Peserta",
  },
  {
    nama: "ARIP RAHMAT SALEH, S.IP.,M.Si",
    ket: "TEKNOLOGI INFORMASI",
    posisi: "Peserta",
  },
  {
    nama: "ARIF SYARIPUDIN, ST",
    ket: "TEKNOLOGI INFORMASI",
    posisi: "Peserta",
  },
  { nama: "ASEP NURJAMAN, S.IP.,M.IP", ket: "PENDATAAN", posisi: "Peserta" },
  { nama: "ANDI YUHANDI, S.IP", ket: "PENDATAAN", posisi: "Peserta" },
  { nama: "TATANG SURYANA", ket: "PENDATAAN", posisi: "Peserta" },
  { nama: "RAHMAT JAMALUDIN", ket: "PENDATAAN", posisi: "Peserta" },
  { nama: "SLAMET SANTOSO, S.Sos", ket: "PENDATAAN", posisi: "Peserta" },
  { nama: "ENOK SRI YUSNAENI, SE", ket: "PENDATAAN", posisi: "Peserta" },
  { nama: "SENDI HALOLONGAN SINAGA", ket: "PENDATAAN", posisi: "Peserta" },
  { nama: "ERIK NUGRAHA, S.IP", ket: "PENDATAAN", posisi: "Peserta" },
  { nama: "ECIN KURAESIN", ket: "PENDATAAN", posisi: "Peserta" },
  { nama: "YUDI NURDIANSYAH, S.IP", ket: "PENAGIHAN", posisi: "Peserta" },
  { nama: "BENI SUPRIYADI, S.IP", ket: "PENAGIHAN", posisi: "Peserta" },
  { nama: "ANI CANTINI, S.IP", ket: "PENAGIHAN", posisi: "Peserta" },
  { nama: "MELDA DENILA, ST., M.Si", ket: "PENAGIHAN", posisi: "Peserta" },
  { nama: "NURHAYATI, S.IP", ket: "PENAGIHAN", posisi: "Peserta" },
  { nama: "KUSNADI, S.IP", ket: "PENAGIHAN", posisi: "Peserta" },
  { nama: "BUDI HARYANA, S.IP", ket: "PENAGIHAN", posisi: "Peserta" },
  { nama: "AI SINTA, SE", ket: "PENAGIHAN", posisi: "Peserta" },
  { nama: "UMI SAOMAH BAROKAH, SE", ket: "SEKRETARIAT", posisi: "Peserta" },
];
